### ISSUE TITLE
Formula Reference

### ISSUE THREAD

**Issue by getSurreal** [jaean123/DeadReckoning-library#2]
Thanks for sharing your work.  I haven't seen this particular formula in any of the papers I've read.  Do you have a reference to where you got it from?  I'd like to read more about it.

```
// Uses 4th order Runge-Kutta to integrate numerically to find position.
	float xNext = xc + dt * v*(2 + cos(dt*w / 2))*cos(theta + dt * w / 2) / 3;
	float yNext = yc + dt * v*(2 + cos(dt*w / 2))*sin(theta + dt * w / 2) / 3;
```

**Comment by jaean123** [comment]
Really sorry for the late reply. Yes, you can find that information here.
https://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/16311/www/s07/labs/NXTLabs/Lab%203.html

**Comment by getSurreal** [comment]
Awesome!  Thanks.
