### ISSUE TITLE
Dead Reckoning library for quadrature Encoders

### ISSUE THREAD

**Issue by subham9777** [jaean123/DeadReckoning-library#4]
Hello @purwar2016 @jaean123 
Can you tell me way to implement the dead reckoning for 2 channels encoders? I thought of implementing but it seems really difficult.

**Comment by jaean123** [comment]
First, you want to familiarize yourself with rotary encoders. Then, you can use a rotary encoder on this library as follows.
The purpose of a two channel encoder is to know the direction of turn. 
When the rotary encoder detects that the wheel turns backwards, you can set the direction by passing -1 to the methods setLeftOmegaDirection or setRightOmegaDirection. When it detects the wheel is turning forwards, pass +1 to those methods. 
Then, use one of the channels for each wheel as leftTicks and rightTicks.
